import { createSlice } from "@reduxjs/toolkit";
import type { PayloadAction } from "@reduxjs/toolkit";
import firstImage from '../images/phone1.jpg';
import secondImage from '../images/phone2.jpg';
import thirdImage from '../images/phone3.jpg';
import airpodsImage from '../images/airpods1.png';

export interface ProductAction {
    id:number,
    title:string,
    url:any,
    description:string,
    real_price:number,
    surcharge:number,
    exchange:boolean,
    prize:boolean;
    discountForPhone:boolean,
    discountForIphone:boolean,
    imgsCollection: Array<any>,
}

const initialState:Array<ProductAction> = [
    {
        id:1,
        title:"Смартфон Samsung Galaxy 9 128 Gb Slim Box черный",
        url:firstImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:6_000_000,
        surcharge:5,
        exchange:true,
        prize:true,
        discountForPhone:true,
        discountForIphone:false,
        imgsCollection:[firstImage,secondImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:2,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:3,
        title:"Наушники Apple Airpods...",
        url:airpodsImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[airpodsImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:4,
        title:"Samsung Galaxy Z Folder...",
        url:thirdImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:5,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:6,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:7,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:8,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:9,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:10,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:11,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:12,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:13,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:14,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:15,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:16,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:17,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:18,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:19,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
      {
        id:20,
        title:"Смартфон Apple iPhone 11 128 Gb Slim Box черный",
        url:secondImage,
        description: "Тип: моноблок (классический) Стандарт: 2G, 3G, 4G (LTE), 5G Операционная система: iOS 14",
        real_price:8_000_000,
        surcharge:4,
        exchange:false,
        prize:true,
        discountForPhone:true,
        discountForIphone:true,
        imgsCollection:[secondImage,firstImage,thirdImage,airpodsImage,secondImage],
      },
];

export const ProductSlice = createSlice({
    name:'products',
    initialState,
    reducers:{}
})

export default ProductSlice.reducer;